### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mgaitan** [sunlightlabs/politwoops-tweet-collector#11]
We at the OpenData group from Cordoba, Argentina, (http://opendatacordoba.org/) are very interested in this library to implement our own "politwoops" service, but it's no clear if it is Libre/Opensource software because it hasn't a clearly defined license.

**Comment by handlers** [comment]
Yeah, we should definitely sort this out — thanks for opening the issue, @mgaitan. @nickom, do you have any details on the licensing for this project?

**Comment by nickom** [comment]
I've added an open source BSD 3 license file here:
https://github.com/sunlightlabs/politwoops-tweet-collector/commit/65c257ea0fd6f5c5d06d2f1e9a7087ae67b1eb4c

Sorry for how long this took and thanks for pointing this out @mgaitan!

**Comment by mgaitan** [comment]
cool, thanks!
